services:
  isaac-lab:
    build: .
    container_name: isaac_lab_pinn
    runtime: nvidia
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    volumes:
      # Проброс X11 для GUI (если нужно)
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      
      # Твой репозиторий с обучением (папка src в корне проекта)
      - ./src:/workspace/IsaacLab/source/extensions/pinn_nav
      
      # Постоянное хранилище (пути из официальной документации Isaac Lab)
      - ./docker_data/cache/kit:/isaac-sim/kit/cache:rw
      - ./docker_data/cache/ov:/root/.cache/ov:rw
      - ./docker_data/cache/pip:/root/.cache/pip:rw
      - ./docker_data/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ./docker_data/cache/computecache:/root/.nv/ComputeCache:rw
      - ./docker_data/logs:/root/.nvidia-omniverse/logs:rw
      - ./docker_data/data:/root/.local/share/ov/data:rw
      - ./docker_data/documents:/root/Documents:rw
      
      # Веса моделей и логи обучения (Checkpoints)
      - ./docker_data/outputs:/workspace/IsaacLab/logs:rw

    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
