services:
  isaac-lab-base:
    build: !reset null
    image: nvcr.io/nvidia/isaac-lab:2.3.2@sha256:388dbc806f48359a964cb9f807feb226da95d0a107f470fdcad9780ea10fe6f2
    volumes:
      - /dev/null:/root/.bash_history
      - ${PIRL_PROJECT_DIR}:/workspace/pirl
